package main

import (
	"encoding/json"
	"log/slog"
	"net/http"
)

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("POST /research/basic", research("basic", "A concise market snapshot generated by the demo seller."))
	mux.HandleFunc("POST /research/board", research("board", "A board-ready market brief generated by the demo seller."))

	slog.Info("starting demo seller", "address", ":8090")
	if err := http.ListenAndServe(":8090", mux); err != nil {
		slog.Error("demo seller stopped", "error", err)
	}
}

func research(tier, summary string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{
			"tier":    tier,
			"summary": summary,
			"request": r.Header.Get("X-AgentPay-Request-Id"),
		})
	}
}
